<?php
/**
 * @file
 * Module that handles customer orders.
 */

/**
 * Implements hook_node_presave().
 */
function custom_order_ride_node_presave($node) {
  if ($node->type == 'ride_booker') {
    // Check if the user has already booked a ride in the last X seconds.
    if (!isset($node->nid)){
      global $user;
      $now = time();
      $grace = 120; // TODO get from settings.php or someplace else.
      $result = db_query('select nid from {node} where changed > (:now - :grace) and uid = :uid', array(':now' => $now, ':grace' => $grace, ':uid' => $user->uid) );
      //drupal_set_message(print_r($node->field_order['und'][0]['target_id'], true));
      //drupal_set_message('<pre>' . print_r($node, true) .'</pre>');
      //*
      if ($result->rowCount() != FALSE) {
        // get the nid and goto that
        $nid = $result->fetchField();
        drupal_goto('node/' . $nid);
      }
    }

    if (!isset($node->field_order['und'][0]['target_id'])) {
      $uid = $node->uid;
      $status = 'cart'; // probably change this to cart
      $type = 'commerce_order';

      $order = commerce_order_new($uid, $status, $type);
      commerce_order_save($order);

      // get the order id of the new order
      $order_id = $order->order_id;

      //update the node so that it is related to the order
      $node->field_order['und'][0]['target_id'] = $order_id;
    }
    //*/
  }
}
